language: node_js
node_js:
  - "4.8"
  - "5.12"
  - "6.10"
  - "7.7"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
before_script:
  - npm install gulp
script:
  - gulp
  - "npm run test-ci"